// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.5.1
// source: gateinfo.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SCGateInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrvType int32  `protobuf:"varint,1,opt,name=SrvType,proto3" json:"SrvType,omitempty"`
	SrvId   int32  `protobuf:"varint,2,opt,name=SrvId,proto3" json:"SrvId,omitempty"`
	AuthKey string `protobuf:"bytes,3,opt,name=AuthKey,proto3" json:"AuthKey,omitempty"`
	Ip      string `protobuf:"bytes,4,opt,name=Ip,proto3" json:"Ip,omitempty"`
	Port    int32  `protobuf:"varint,5,opt,name=Port,proto3" json:"Port,omitempty"`
}

func (x *SCGateInfo) Reset() {
	*x = SCGateInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateinfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCGateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCGateInfo) ProtoMessage() {}

func (x *SCGateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gateinfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCGateInfo.ProtoReflect.Descriptor instead.
func (*SCGateInfo) Descriptor() ([]byte, []int) {
	return file_gateinfo_proto_rawDescGZIP(), []int{0}
}

func (x *SCGateInfo) GetSrvType() int32 {
	if x != nil {
		return x.SrvType
	}
	return 0
}

func (x *SCGateInfo) GetSrvId() int32 {
	if x != nil {
		return x.SrvId
	}
	return 0
}

func (x *SCGateInfo) GetAuthKey() string {
	if x != nil {
		return x.AuthKey
	}
	return ""
}

func (x *SCGateInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SCGateInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type CSSessionBundle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Ts  int64  `protobuf:"varint,2,opt,name=Ts,proto3" json:"Ts,omitempty"`
}

func (x *CSSessionBundle) Reset() {
	*x = CSSessionBundle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateinfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSSessionBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSSessionBundle) ProtoMessage() {}

func (x *CSSessionBundle) ProtoReflect() protoreflect.Message {
	mi := &file_gateinfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSSessionBundle.ProtoReflect.Descriptor instead.
func (*CSSessionBundle) Descriptor() ([]byte, []int) {
	return file_gateinfo_proto_rawDescGZIP(), []int{1}
}

func (x *CSSessionBundle) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CSSessionBundle) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

type CSSessionAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LogicNo uint32 `protobuf:"varint,1,opt,name=LogicNo,proto3" json:"LogicNo,omitempty"`
}

func (x *CSSessionAck) Reset() {
	*x = CSSessionAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateinfo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSSessionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSSessionAck) ProtoMessage() {}

func (x *CSSessionAck) ProtoReflect() protoreflect.Message {
	mi := &file_gateinfo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSSessionAck.ProtoReflect.Descriptor instead.
func (*CSSessionAck) Descriptor() ([]byte, []int) {
	return file_gateinfo_proto_rawDescGZIP(), []int{2}
}

func (x *CSSessionAck) GetLogicNo() uint32 {
	if x != nil {
		return x.LogicNo
	}
	return 0
}

var File_gateinfo_proto protoreflect.FileDescriptor

var file_gateinfo_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x67, 0x61, 0x74, 0x65, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x7a, 0x0a, 0x0a, 0x53, 0x43,
	0x47, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x72, 0x76, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x53, 0x72, 0x76, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x72, 0x76, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x53, 0x72, 0x76, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x75, 0x74, 0x68,
	0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x75, 0x74, 0x68, 0x4b,
	0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x49, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x22, 0x33, 0x0a, 0x0f, 0x43, 0x53, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x42, 0x75, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x54,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x54, 0x73, 0x22, 0x28, 0x0a, 0x0c, 0x43,
	0x53, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x4c,
	0x6f, 0x67, 0x69, 0x63, 0x4e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x4c, 0x6f,
	0x67, 0x69, 0x63, 0x4e, 0x6f, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gateinfo_proto_rawDescOnce sync.Once
	file_gateinfo_proto_rawDescData = file_gateinfo_proto_rawDesc
)

func file_gateinfo_proto_rawDescGZIP() []byte {
	file_gateinfo_proto_rawDescOnce.Do(func() {
		file_gateinfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_gateinfo_proto_rawDescData)
	})
	return file_gateinfo_proto_rawDescData
}

var file_gateinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gateinfo_proto_goTypes = []interface{}{
	(*SCGateInfo)(nil),      // 0: protocol.SCGateInfo
	(*CSSessionBundle)(nil), // 1: protocol.CSSessionBundle
	(*CSSessionAck)(nil),    // 2: protocol.CSSessionAck
}
var file_gateinfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateinfo_proto_init() }
func file_gateinfo_proto_init() {
	if File_gateinfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gateinfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCGateInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateinfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSSessionBundle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gateinfo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSSessionAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gateinfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateinfo_proto_goTypes,
		DependencyIndexes: file_gateinfo_proto_depIdxs,
		MessageInfos:      file_gateinfo_proto_msgTypes,
	}.Build()
	File_gateinfo_proto = out.File
	file_gateinfo_proto_rawDesc = nil
	file_gateinfo_proto_goTypes = nil
	file_gateinfo_proto_depIdxs = nil
}
