// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.5.1
// source: packetid.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MmoPacketID int32

const (
	MmoPacketID_PACKET_GB_UNKNOW        MmoPacketID = 0
	MmoPacketID_PACKET_GB_CUR_LOAD      MmoPacketID = 1000
	MmoPacketID_PACKET_GB_STATE_SWITCH  MmoPacketID = 1001
	MmoPacketID_PACKET_SC_GATEINFO      MmoPacketID = 1002
	MmoPacketID_PACKET_CS_SESSIONBUNDLE MmoPacketID = 1003
	MmoPacketID_PACKET_CS_SESSIONACK    MmoPacketID = 1004
)

// Enum value maps for MmoPacketID.
var (
	MmoPacketID_name = map[int32]string{
		0:    "PACKET_GB_UNKNOW",
		1000: "PACKET_GB_CUR_LOAD",
		1001: "PACKET_GB_STATE_SWITCH",
		1002: "PACKET_SC_GATEINFO",
		1003: "PACKET_CS_SESSIONBUNDLE",
		1004: "PACKET_CS_SESSIONACK",
	}
	MmoPacketID_value = map[string]int32{
		"PACKET_GB_UNKNOW":        0,
		"PACKET_GB_CUR_LOAD":      1000,
		"PACKET_GB_STATE_SWITCH":  1001,
		"PACKET_SC_GATEINFO":      1002,
		"PACKET_CS_SESSIONBUNDLE": 1003,
		"PACKET_CS_SESSIONACK":    1004,
	}
)

func (x MmoPacketID) Enum() *MmoPacketID {
	p := new(MmoPacketID)
	*p = x
	return p
}

func (x MmoPacketID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MmoPacketID) Descriptor() protoreflect.EnumDescriptor {
	return file_packetid_proto_enumTypes[0].Descriptor()
}

func (MmoPacketID) Type() protoreflect.EnumType {
	return &file_packetid_proto_enumTypes[0]
}

func (x MmoPacketID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MmoPacketID.Descriptor instead.
func (MmoPacketID) EnumDescriptor() ([]byte, []int) {
	return file_packetid_proto_rawDescGZIP(), []int{0}
}

var File_packetid_proto protoreflect.FileDescriptor

var file_packetid_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2a, 0xab, 0x01, 0x0a, 0x0b, 0x4d,
	0x6d, 0x6f, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x41,
	0x43, 0x4b, 0x45, 0x54, 0x5f, 0x47, 0x42, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x10, 0x00,
	0x12, 0x17, 0x0a, 0x12, 0x50, 0x41, 0x43, 0x4b, 0x45, 0x54, 0x5f, 0x47, 0x42, 0x5f, 0x43, 0x55,
	0x52, 0x5f, 0x4c, 0x4f, 0x41, 0x44, 0x10, 0xe8, 0x07, 0x12, 0x1b, 0x0a, 0x16, 0x50, 0x41, 0x43,
	0x4b, 0x45, 0x54, 0x5f, 0x47, 0x42, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x57, 0x49,
	0x54, 0x43, 0x48, 0x10, 0xe9, 0x07, 0x12, 0x17, 0x0a, 0x12, 0x50, 0x41, 0x43, 0x4b, 0x45, 0x54,
	0x5f, 0x53, 0x43, 0x5f, 0x47, 0x41, 0x54, 0x45, 0x49, 0x4e, 0x46, 0x4f, 0x10, 0xea, 0x07, 0x12,
	0x1c, 0x0a, 0x17, 0x50, 0x41, 0x43, 0x4b, 0x45, 0x54, 0x5f, 0x43, 0x53, 0x5f, 0x53, 0x45, 0x53,
	0x53, 0x49, 0x4f, 0x4e, 0x42, 0x55, 0x4e, 0x44, 0x4c, 0x45, 0x10, 0xeb, 0x07, 0x12, 0x19, 0x0a,
	0x14, 0x50, 0x41, 0x43, 0x4b, 0x45, 0x54, 0x5f, 0x43, 0x53, 0x5f, 0x53, 0x45, 0x53, 0x53, 0x49,
	0x4f, 0x4e, 0x41, 0x43, 0x4b, 0x10, 0xec, 0x07, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_packetid_proto_rawDescOnce sync.Once
	file_packetid_proto_rawDescData = file_packetid_proto_rawDesc
)

func file_packetid_proto_rawDescGZIP() []byte {
	file_packetid_proto_rawDescOnce.Do(func() {
		file_packetid_proto_rawDescData = protoimpl.X.CompressGZIP(file_packetid_proto_rawDescData)
	})
	return file_packetid_proto_rawDescData
}

var file_packetid_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_packetid_proto_goTypes = []interface{}{
	(MmoPacketID)(0), // 0: protocol.MmoPacketID
}
var file_packetid_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_packetid_proto_init() }
func file_packetid_proto_init() {
	if File_packetid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_packetid_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packetid_proto_goTypes,
		DependencyIndexes: file_packetid_proto_depIdxs,
		EnumInfos:         file_packetid_proto_enumTypes,
	}.Build()
	File_packetid_proto = out.File
	file_packetid_proto_rawDesc = nil
	file_packetid_proto_goTypes = nil
	file_packetid_proto_depIdxs = nil
}
