// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.5.1
// source: keepalive.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SSPacketKeepAlive struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag int32 `protobuf:"varint,1,opt,name=Flag,proto3" json:"Flag,omitempty"`
}

func (x *SSPacketKeepAlive) Reset() {
	*x = SSPacketKeepAlive{}
	if protoimpl.UnsafeEnabled {
		mi := &file_keepalive_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSPacketKeepAlive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSPacketKeepAlive) ProtoMessage() {}

func (x *SSPacketKeepAlive) ProtoReflect() protoreflect.Message {
	mi := &file_keepalive_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSPacketKeepAlive.ProtoReflect.Descriptor instead.
func (*SSPacketKeepAlive) Descriptor() ([]byte, []int) {
	return file_keepalive_proto_rawDescGZIP(), []int{0}
}

func (x *SSPacketKeepAlive) GetFlag() int32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

var File_keepalive_proto protoreflect.FileDescriptor

var file_keepalive_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6b, 0x65, 0x65, 0x70, 0x61, 0x6c, 0x69, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x27, 0x0a, 0x11, 0x53,
	0x53, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x46, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x46, 0x6c, 0x61, 0x67, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_keepalive_proto_rawDescOnce sync.Once
	file_keepalive_proto_rawDescData = file_keepalive_proto_rawDesc
)

func file_keepalive_proto_rawDescGZIP() []byte {
	file_keepalive_proto_rawDescOnce.Do(func() {
		file_keepalive_proto_rawDescData = protoimpl.X.CompressGZIP(file_keepalive_proto_rawDescData)
	})
	return file_keepalive_proto_rawDescData
}

var file_keepalive_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_keepalive_proto_goTypes = []interface{}{
	(*SSPacketKeepAlive)(nil), // 0: protocol.SSPacketKeepAlive
}
var file_keepalive_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_keepalive_proto_init() }
func file_keepalive_proto_init() {
	if File_keepalive_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_keepalive_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSPacketKeepAlive); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_keepalive_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_keepalive_proto_goTypes,
		DependencyIndexes: file_keepalive_proto_depIdxs,
		MessageInfos:      file_keepalive_proto_msgTypes,
	}.Build()
	File_keepalive_proto = out.File
	file_keepalive_proto_rawDesc = nil
	file_keepalive_proto_goTypes = nil
	file_keepalive_proto_depIdxs = nil
}
